#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}/../tools" || exit 1
TOOLS_DIR=$(pwd)
cd "${DIR}" || exit 1

eval `CONFIG_FILE="${DIR}/../.config" "${TOOLS_DIR}/explode_config" "$@"`

cmdline=''

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    *)
    # unknown option
    cmdline=$cmdline' '$key
    ;;  esac
  shift # past argument or value
done

"${DIR}/bin/helm/helm" ${cmdline}
