#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}/../tools"
TOOLS_DIR=$(pwd)
cd "${DIR}" || exit 1

namespace='myproduct'
kubeconfig="${DIR}/config/kube.yaml"

eval `CONFIG_FILE="${DIR}/../.config" "${TOOLS_DIR}/explode_config" "$@"`

cmdline=''

while [[ $# > 0 ]]
do
  key="$1"
  case $key in
    -n|--namespace)
      namespace="$2"
      shift
    ;;
    -k|--kubeconfig)
      kubeconfig="$2"
      shift
    ;;
    *)
    # unknown option
    cmdline=$cmdline' '$key
    ;;  esac
  shift # past argument or value
done

"${DIR}/bin/kubectl/kubectl" --kubeconfig "${kubeconfig}" --namespace "${namespace}" ${cmdline}
