#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}" || exit 1

serviceVersion=v1
serviceName=false
serviceType=false

eval `CONFIG_FILE="${DIR}/../.config" "${DIR}/explode_config" "$@"`

function checkServiceType {
  serviceType=$(echo "${serviceType}" | awk '{print tolower($0)}')
  if [[ "${serviceType}" == "js" ]] || [[ "${serviceType}" == "node" ]] || [[ "${serviceType}" == "nodejs" ]]; then
    serviceType="node"
    return 1;
  fi
  if [[ "${serviceType}" == "py" ]] || [[ "${serviceType}" == "python" ]]; then
    return 1;
  fi
  if [[ "${serviceType}" == "cs" ]] || [[ "${serviceType}" == "c#" ]]; then
    serviceType="cs"
    return 1;
  fi

  echo "Specified serviceType must be one of; node, python, c#"
  exit 1
}

while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
    -n|--serviceName|--servicename)
      serviceName="$2"
      shift
    ;;
    -t|--serviceType|--servicetype)
      serviceType="$2"
      shift
    ;;
    *)
    # unknown option
    ;;  esac
  shift # past argument or value
done

checkServiceType

if [[ ${serviceName} == false ]]; then
  echo "Must supply serviceName"
  exit 1
fi

if [[ ${serviceType} == false ]]; then
  echo "Must supply serviceType"
  exit 1
fi

btd=$(pwd)

cd ..

cd "./services/" || exit 1
sd=$(pwd)

echo "Creating project ${serviceName}"

rm -rf "${sd}/${serviceName}"
mkdir "${sd}/${serviceName}"
cp -ar "${sd}/__base/${serviceType}/." "${sd}/${serviceName}/"
rm -rf "${sd}/${serviceName}/src/samples"
rm -rf "${sd}/${serviceName}/src/node_modules"
cd "${sd}/${serviceName}" || exit 1

echo "# ${serviceName}

Description of what the service does belongs here.
">"$sd/$serviceName/readme.md"

if test -f "init.sh"; then
  sh init.sh "$@" && rm -f init.sh || exit 1
fi

cd "${sd}/${serviceName}" || exit 1
