#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR" || exit 1

btd=$(pwd)

cd ..
wd=$(pwd)

cd "$wd/services/"
sd=$(pwd)
services=$(find . -type f -name 'build.sh' -exec dirname "{}" \; )

#COPY_FILES=(
#  .dockerignore
#  .gitignore
#  build.sh
#  Dockerfile
#)

COPY_FILES=(
  build.sh
)

for servicePath in $services; do
  cd "$sd/$servicePath" || exit 1
  service=$(basename $servicePath)
  echo ""
  echo "Updating $service"
  for filename in ${COPY_FILES[@]}; do
    echo "Copying $filename"
    rm -f "$sd/$servicePath/$filename"
    cp "$btd/$filename" "$sd/$servicePath/$filename"
    git add "$sd/$servicePath/$filename"
  done
done

git commit -m "Update build tools"
git push origin main
